// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TinaKingSystem.Entities;

[Table("Client")]
internal partial class Client
{
    [Key]
    public int ClientID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Province { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    [InverseProperty("Client")]
    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();
}