// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TinaKingSystem.Entities;

[Table("Document")]
internal partial class Document
{
    [Key]
    public int DocumentID { get; set; }

    public int? ClientID { get; set; }

    public int PackageID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string DocumentName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string DocumentNumber { get; set; }

    public double? DocumentSize { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Documents")]
    public virtual Client Client { get; set; }

    [ForeignKey("PackageID")]
    [InverseProperty("Documents")]
    public virtual Package Package { get; set; }
}