// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TinaKingSystem.Entities;

[Table("Employee")]
internal partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string employeeName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleName { get; set; }

    public int RoleID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Province { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}